---
abstract: 'Gradually enforce coding standards with Dist::Zilla'
author:
  - 'Christian Walde <mithaldu@yahoo.de>'
build_requires:
  Capture::Tiny: 0
  Dist::Zilla::Tester: 0
  JSON: 2
  Params::Util: 0
  Path::Class: 0
  Sub::Exporter: 0
  Test::More: 0.88
  Test::Perl::Critic::Progressive: 0
  Try::Tiny: 0
  YAML::Tiny: 0
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101580, CPAN::Meta::Converter version 2.101580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ProgCriticTests
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  perl: 5.008
version: 1.101582
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: AutoVersion
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: AutoPrereq
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::Readme
      name: Readme
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: KwaliteeTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::ProgCriticTests
      name: ProgCriticTests
      version: 1.101570
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101580
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101580
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101580
